**22.7.24**

In [19]:
import pandas as pd

In [21]:
#import pandas as p
l1=[i for i in range (1,11)]
l2=[i*i for i in l1]
l3=[i**3 for i in l1]
col=['num','sqr','cub']
df1=pd.DataFrame(zip(l1,l2,l3),columns=col)
df1


num  sqr   cub
0    1    1     1
1    2    4     8
2    3    9    27
3    4   16    64
4    5   25   125
5    6   36   216
6    7   49   343
7    8   64   512
8    9   81   729
9   10  100  1000

**sstep-8**
**drop the row**

- drop the column and drop the rows both are similar only

- the only difference is axis

    - axis=0 represents rows

    - by default axis=0 availabe

    - which means if we provide any value,it will represent row only

In [4]:
df1.drop()
if we run this we will get error
by default axis=0 which represents about rows
but 'number' is a column
if u want to drop row, then provide the row index

SyntaxError: invalid syntax (3029587032.py, line 2)

In [24]:

df1.drop(4)

num  sqr   cub
0    1    1     1
1    2    4     8
2    3    9    27
3    4   16    64
5    6   36   216
6    7   49   343
7    8   64   512
8    9   81   729
9   10  100  1000

In [26]:
df1.drop([0,1],axis=1)
#[0,1] index
#axis=1 column
#error

KeyError: '[0, 1] not found in axis'

**step-9**

**how to select the column**

In [28]:
df1['num']

#series type
# no column name display
# whenever u see this type:serise type

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: num, dtype: int64

In [30]:
type(df1['num'])

pandas.core.series.Series

In [32]:
df1[['num']]
#data frame 

num
0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
9   10

In [34]:
type(df1[['num']])

pandas.core.frame.DataFrame

In [36]:
df1.num #it is same as df1['num]

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: num, dtype: int64

- df1['num']: series type

- df1[['num']]: dataframe type

- df1.num:series type

In [39]:
col=['num','sqr']
df1[col]

num  sqr
0    1    1
1    2    4
2    3    9
3    4   16
4    5   25
5    6   36
6    7   49
7    8   64
8    9   81
9   10  100

- all values comes in an array

- array means it is a list of elements only using numpy package 

- generally elements present in 4 ways

    - list: array with numpy package
    
    - numpy array: array with numpy package
        
    - tensors: tensorflow package
        
    - torch: pytorch package

In [42]:
li1=[1,2,3,4]
li1

[1, 2, 3, 4]

In [44]:
import numpy as np
np.array(li1)

array([1, 2, 3, 4])

In [46]:
li1=[1,2,3]
li2=[10,20,30]
li1+li2

[1, 2, 3, 10, 20, 30]

In [48]:
l1=np.array(li1)
l2=np.array(li2)
l1+l2

array([11, 22, 33])

In [50]:
df1['num'].values

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int64)

In [52]:
df1['Number']=df1['num'].values
df1

num  sqr   cub  Number
0    1    1     1       1
1    2    4     8       2
2    3    9    27       3
3    4   16    64       4
4    5   25   125       5
5    6   36   216       6
6    7   49   343       7
7    8   64   512       8
8    9   81   729       9
9   10  100  1000      10

In [ ]:
**step-10**

**save the dataframe**

- dataframe we can save in



In [54]:
#case-1:saving file at same location
#no need to provide directory path
#directory give only name of the file
#and extension

In [56]:
#dataframe name df1
df1.to_csv('Data.csv')
df1.to_excel('DATA1.xlsx')

**step-11**

**how to read a data frame**

    

In [58]:
import pandas as pd
pd.read_csv('Data.csv')

Unnamed: 0  num  sqr   cub  Number
0           0    1    1     1       1
1           1    2    4     8       2
2           2    3    9    27       3
3           3    4   16    64       4
4           4    5   25   125       5
5           5    6   36   216       6
6           6    7   49   343       7
7           7    8   64   512       8
8           8    9   81   729       9
9           9   10  100  1000      10

**step-12**

**how to avoid index column**

- while we save the dataframe

- automaticaly a new column will create

- that we need to avoid

- permisson denied means close the data file from laptop

In [61]:
pd.read_excel('DATA1.xlsx')

Unnamed: 0  num  sqr   cub  Number
0           0    1    1     1       1
1           1    2    4     8       2
2           2    3    9    27       3
3           3    4   16    64       4
4           4    5   25   125       5
5           5    6   36   216       6
6           6    7   49   343       7
7           7    8   64   512       8
8           8    9   81   729       9
9           9   10  100  1000      10

In [63]:
#dataframe name df1
df1.to_csv('Data.csv',index=False)
df1.to_excel('DATA1.xlsx',index=False)

In [69]:
pd.read_csv('Data.csv')

num  sqr   cub  Number
0    1    1     1       1
1    2    4     8       2
2    3    9    27       3
3    4   16    64       4
4    5   25   125       5
5    6   36   216       6
6    7   49   343       7
7    8   64   512       8
8    9   81   729       9
9   10  100  1000      10

In [67]:
pd.read_excel('DATA1.xlsx')


num  sqr   cub  Number
0    1    1     1       1
1    2    4     8       2
2    3    9    27       3
3    4   16    64       4
4    5   25   125       5
5    6   36   216       6
6    7   49   343       7
7    8   64   512       8
8    9   81   729       9
9   10  100  1000      10